---
version: '3.8'
services:
  app:
    command: poetry run python api.py
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis  # Redis servisinin adını "redis" olarak belirtin
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
